language: go
go:
- 1.7
- 1.8
- 1.9
- 1.10.x
- 1.11
before_install:
- sudo apt-get install moreutils
- go get -u github.com/mattn/goveralls
- wget http://www.modbusdriver.com/downloads/diagslave.2.12.zip
- mkdir diagslave
- unzip -d diagslave diagslave.2.12.zip
- chmod u+x diagslave/linux/diagslave
- export PATH="$PATH:$PWD/diagslave/linux/"
script:
- goveralls -service=travis-ci -race | pee cat 'grep PASS &>/dev/null'
git:
  depth: 3
notifications:
  email: false
  slack:
    secure: omXbCVRER63WPu9Q9oLcqhogNCLyZQIpJoq/zt30OJ9HUFTdXa1h3Ghm5Tihm7uXf5KFpVs6D+7u7D7CDX1Pdvw5FGNNp+Dg3GmSnykNW24uTuflhGi0uye1yvehJL9L2LZW7/CP9uDfehZaCXDmgNrA1aIL9uXRLEL+xkN+R/Ce3ES22X2qBvJzSev0P9kCS98eoq4XslD+CHEGv4UN74fV2rKP/DTJTXcDnezrhSeLOxyedyFKLq3iPSm0ElchChSU7bimtMQRVCy4fply4PZR8ZRcilCcIjRyr6Qz+dKFsaJRHygRws6MK7WnkxG5dH7ARHZx2Wtxl/ULecszIrUAWSkIM/hqWRSQtqJ7sXGWcR95n96HwHJylvpkw+pgCAQCvXZw8oUjgyDC5+l4Kixk5LhLvT7u7zadUsq5CZTfAv8YmpY03qic/bsJ1PJQjdV4PywdrjeTKEJef6fw+XTQwRFMEm81TPTyT4e0MvNAtTgKE/YdiH8IDByzeUVrttGahzA9ThiUPVTh+6cYVoGfgvuDOxIyoRFV2odVGdgU6vPvRh+bRcp/UeD3ech0sa62A33IKpHlzdsor4FOjAfp72c8QmC1XcTwd+RBJSxxds/2JxKZB2mwJuMcxfaOlR2nZQJLIaCzmMn4vdqGnfLiX+cFeqxHqkIhktZ4bTM=
env:
  global:
  - GO111MODULE=on
